### ISSUE TITLE
How to place the search input DIV above the map?

### ISSUE THREAD

**Issue by canosso** [smeijer/L.GeoSearch#38]
Hello,
is it possible to place the search input above the map, similiar to this mobile map, http://m.wien.gv.at/stadtplan/ (it is also a Leaflet map)?

I tested the Demo with my mobile phone, the search input was difficult to find and it was not in the middle of the map. 

Thank you in advance for any help.

**Comment by smeijer** [comment]
I'm aware this is to late for the issue reporter. But for future reference:

To change the position of the search-bar, one can simply override some styles:

```css
.leaflet-control-geosearch form {
  display: block;
  position: fixed;
  top: 10px;
  left: 10px;
  right: 10px;
}

.leaflet-control-geosearch form input {
  width: 100%;
}

.leaflet-control-geosearch .leaflet-bar-part {
  display: none;
}
```
